name: quizz_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

# 1. TAMBAHKAN DEPENDENSI INI
dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  google_fonts: ^6.1.0
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # 2. TAMBAHKAN BAGIAN ASET INI
  assets:
    - assets/images/quiz_logo.png

  # 3. TAMBAHKAN BAGIAN FONT INI
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700